### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TrinityDevelopers** [Virtualoso/NativeTools#4]
- Add NinePatchLayers
- Add CreativeTab class

**Comment by rekmolly** [comment]
Nice

**Comment by Khristian-kun** [comment]
almost done this TODO, next changes should be add the tab slots, category custom image, etc...?

**Comment by TrinityDevelopers** [comment]
Yes, that is what I am working on now! :)

**Comment by ThePixelGamer** [comment]
We finished this a few days ago lol
