### ISSUE TITLE
Andy where are you?

### ISSUE THREAD

**Issue by ThePixelGamer** [Virtualoso/NativeTools#5]
Andy what happened to you on twitter? Are you coming back? Could you please tell us what's happening?

**Comment by TrinityDevelopers** [comment]
It's really complicated... I may come back, but not for a while. I just
have more important things like school in my life, and I don't have the
time to not anymore.  I will try to explain more later.

**Comment by ThePixelGamer** [comment]
Could you at least make a chat where we can talk in private? Even if you don't program anymore I would still like to talk to you.
